name: screen_adaptive_plus
description: A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
version: 1.0.0
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
